<?php

/**
 * This is the model base class for the table "banner".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Banner".
 *
 * Columns in table "banner" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $descripcion
 * @property string $imagen
 * @property string $alt_imagen
 * @property integer $visible
 *
 */
abstract class BaseBanner extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'banner';
    }

    public static function representingColumn() {
        return 'alt_imagen';
    }

    public function rules() {
        return array(
            array('descripcion, imagen', 'required'),
            array('visible', 'numerical', 'integerOnly'=>true),
            array('imagen', 'length', 'max'=>150),
            array('alt_imagen', 'length', 'max'=>100),
            array('alt_imagen, visible', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, descripcion, imagen, alt_imagen, visible', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'descripcion' => Yii::t('app', 'Descripción'),
                'imagen' => Yii::t('app', 'Imagen'),
                'alt_imagen' => Yii::t('app', 'Alt Imagen'),
                'visible' => Yii::t('app', 'Visible'),
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('descripcion', $this->descripcion, true);
        $criteria->compare('imagen', $this->imagen, true);
        $criteria->compare('alt_imagen', $this->alt_imagen, true);
        $criteria->compare('visible', $this->visible);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}