<?php

/**
 * This is the model base class for the table "pedido".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Pedido".
 *
 * Columns in table "pedido" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $empresa
 * @property string $correo
 * @property string $nombre
 * @property string $descripcion
 *
 */
abstract class BasePedido extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'pedido';
    }

    public static function representingColumn() {
        return 'empresa';
    }

    public function rules() {
        return array(
            array('empresa, correo, nombre, descripcion', 'required'),
            array('empresa', 'length', 'max'=>255),
            array('correo', 'length', 'max'=>100),
            array('nombre', 'length', 'max'=>120),
            array('id, empresa, correo, nombre, descripcion', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'empresa' => Yii::t('app', 'Empresa'),
                'correo' => Yii::t('app', 'Correo'),
                'nombre' => Yii::t('app', 'Nombre'),
                'descripcion' => Yii::t('app', 'Descripción'),
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('empresa', $this->empresa, true);
        $criteria->compare('correo', $this->correo, true);
        $criteria->compare('nombre', $this->nombre, true);
        $criteria->compare('descripcion', $this->descripcion, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}